main.cpp(17), func(...): throwing just because
