terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
./cmd.sh: line 1: 13211 Aborted                 (core dumped) ./a.out
