terminate called after throwing an instance of 'BaseException'
  what():  computation aborted with answer: 42
bash: line 8: 19651 Aborted                 (core dumped) ./a.out
