terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
bash: line 7: 12278 Aborted                 (core dumped) ./a.out
